spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com.atomikos: INFO
    org.hibernate.SQL: DEBUG
